// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsLOYh-DLfALpsJKMtf_kewabDp9D6aBw',
    appId: '1:545674316584:web:5b5b47d4301862ea155e1d',
    messagingSenderId: '545674316584',
    projectId: 'esteticaflutter',
    authDomain: 'esteticaflutter.firebaseapp.com',
    storageBucket: 'esteticaflutter.appspot.com',
    measurementId: 'G-V7PHXS0HVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdkehHiowMSYMwpaMt-Fg5V3bDJkbpcBA',
    appId: '1:545674316584:android:a6bcbfc3eeeeefd1155e1d',
    messagingSenderId: '545674316584',
    projectId: 'esteticaflutter',
    storageBucket: 'esteticaflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwu-oWGcGYeJVv0Ge1OtRkp4zRuMSrF18',
    appId: '1:545674316584:ios:3ead6c972d855735155e1d',
    messagingSenderId: '545674316584',
    projectId: 'esteticaflutter',
    storageBucket: 'esteticaflutter.appspot.com',
    iosClientId: '545674316584-ejrt661jftvnvqjsg6a57nv3tb8c3m25.apps.googleusercontent.com',
    iosBundleId: 'com.rdes.esteticaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwu-oWGcGYeJVv0Ge1OtRkp4zRuMSrF18',
    appId: '1:545674316584:ios:3ead6c972d855735155e1d',
    messagingSenderId: '545674316584',
    projectId: 'esteticaflutter',
    storageBucket: 'esteticaflutter.appspot.com',
    iosClientId: '545674316584-ejrt661jftvnvqjsg6a57nv3tb8c3m25.apps.googleusercontent.com',
    iosBundleId: 'com.rdes.esteticaApp',
  );
}
